index:
    path: /
    controller: App\Controller\HomeController::index

signUpUser:
    path: /register/user
    controller: App\Controller\RegistrationController::UserRegister

signUpTeacher:
    path: /register/teacher
    controller: App\Controller\RegistrationController::TeacherRegister

EditTeacher:
    path: /profile/teacher/update
    controller: App\Controller\RegistrationController::TeacherRegister

EditUser:
    path: /profile/user/update
    controller: App\Controller\RegistrationController::UserRegister

profileUser:
    path: /profile/user
    controller: App\Controller\UserController::UserProfile

profileTeacher:
    path: /profile/teacher
    controller: App\Controller\UserController::TeacherProfile

AlLessonRequestOwnedByUser:
    path: /lessonrequest/
    controller: App\Controller\LessonRequestController::UserLessonsRequests

AlLessonRequestOwnedByUser1:
    path: /lessonrequests/user/
    controller: App\Controller\LessonRequestController::getUserLessonsRequests

AlLessonRequest:
    path: /lessonrequests/all
    controller: App\Controller\LessonRequestController::getAllLessonsRequests

AllMessages:
    path: /messages/all
    controller: App\Controller\MessageController::showAllConversations

GetConversationMessages:
    path: /messages/get/{id1}/{id2}
    controller: App\Controller\MessageController::getMessages

ShowConversation:
    path: /messages/{id1}/{id2}
    controller: App\Controller\MessageController::showConversation

